# Generated by Django 4.1.4 on 2022-12-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="phone",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
