# Generated by Django 4.1.4 on 2022-12-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("JUS", "Юстиция"),
                    ("BUI", "Строителстьво"),
                    ("EDU", "Образование"),
                ],
                default="JUS",
                max_length=20,
            ),
        ),
    ]
